# https://godoc.org/golang.org/x/tools/cmd/goimports
# go get golang.org/x/tools/cmd/goimports

# https://github.com/go-critic/go-critic
# GO111MODULE=on go get -v -u github.com/go-critic/go-critic/cmd/gocritic
---
- repo: git://github.com/TekWizely/pre-commit-golang
  rev: v0.8.0
  hooks:
    -   id: go-build-mod
    -   id: go-test-mod
        # Formatters
    -   id: go-fmt
    -   id: go-imports
        # Linters
#    -   id: go-lint
    -   id: go-critic